# Generated by Django 4.1.4 on 2022-12-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
